### ISSUE TITLE
能支持 embed 状态的非图片的文件链接在typora中的显示样式优化

### ISSUE THREAD

**Issue by at2008** [typora-community-plugin/typora-community-plugin#33]
比如：`![测试.json](测试.json)`

目前 typora 是这样显示的

![image](https://github.com/user-attachments/assets/4ca4dc3b-98f3-46ae-b47b-fc97718509a3)

obsidian 是这样显示的

![image](https://github.com/user-attachments/assets/be7ec991-cf6d-49d8-84c7-59c0e7c086ea)

**Comment by plylrnsdy** [comment]
这个用 css 就可以实现吧

```css
.md-image[data-src$=".json"] {
    display: inline-block;
    width: 100%;
    background: #fafafa;
    text-align: center;
}
```
